version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    image: nextcloud
    restart: always
    container_name: nextcloud-app
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    depends_on:
      - db

volumes:
  db:
  nextcloud: