version: '3'

services:
  # Web Application
  web:
    image: php:8.2-apache
    container_name: envirotech-web
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - envirotech-network
    depends_on:
      - temperature-sensor
      - ph-sensor
      - tds-sensor

  # Temperature Sensor Service (Spring Boot)
  temperature-sensor:
    build:
      context: ./sensors/temperature
      dockerfile: Dockerfile
    container_name: envirotech-temp-sensor
    environment:
      - SENSOR_TYPE=temperature
      - READING_INTERVAL=30
      - SPRING_PROFILES_ACTIVE=prod
      - FIREBASE_DB_URL=${FIREBASE_DB_URL}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - envirotech-network
    volumes:
      - ./sensors/temperature:/app
    restart: unless-stopped

  # pH Sensor Service (Spring Boot)
  ph-sensor:
    build:
      context: ./sensors/ph
      dockerfile: Dockerfile
    container_name: envirotech-ph-sensor
    environment:
      - SENSOR_TYPE=ph
      - READING_INTERVAL=60
      - SPRING_PROFILES_ACTIVE=prod
      - FIREBASE_DB_URL=${FIREBASE_DB_URL}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    ports:
      - "8081:8080"
    networks:
      - envirotech-network
    volumes:
      - ./sensors/ph:/app
    restart: unless-stopped

  # TDS Sensor Service (Spring Boot)
  tds-sensor:
    build:
      context: ./sensors/tds
      dockerfile: Dockerfile
    container_name: envirotech-tds-sensor
    environment:
      - SENSOR_TYPE=tds
      - READING_INTERVAL=60
      - SPRING_PROFILES_ACTIVE=prod
      - FIREBASE_DB_URL=${FIREBASE_DB_URL}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    ports:
      - "8082:8080"
    networks:
      - envirotech-network
    volumes:
      - ./sensors/tds:/app
    restart: unless-stopped

networks:
  envirotech-network:
    driver: bridge 